apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: 418272785046.dkr.ecr.ap-northeast-2.amazonaws.com/todo:1.0
          ports:
            - containerPort: 8080
