spring.datasource.url=jdbc:h2:mem:todo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.oauth2.client.registration.cognito.client-id=c995189j0efrd7lslclk9k683
spring.security.oauth2.client.registration.cognito.client-secret=gjkup76219q4tnufmvg389s645ilte0cp2tnhguh5uil3rup64o
spring.security.oauth2.client.registration.cognito.scope=openid
spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code

# ?? baseUrl ?? ??
# spring.security.oauth2.client.registration.cognito.redirect-uri={baseUrl}/login/oauth2/code/cognito

# ?? redirect URI
#spring.security.oauth2.client.registration.cognito.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.cognito.redirect-uri=https://taskall.click/login/oauth2/code/cognito
# ALB ? ??
server.forward-headers-strategy=framework

spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_abT0Vj9BI

management.endpoints.web.exposure.include=health

server.address=0.0.0.0
server.port=8080